### ISSUE TITLE
Multiprocessing errors on 2.7 and 3.6

### ISSUE THREAD

**Issue by cjhopp** [djpugh/MTfit#18]
Hi David,

I've been having a go at the tutorial data and have been running into issues when running with multiprocessing. The examples work fine on a single thread. 

I've compiled from the most recent commits to develop (as of about 24 hours ago) and have run into the same issue on both py 2.7 and 3.6, in separate conda envs.

I ran mtfit from the command prompt like so:

```
mtfit --location_pdf_file_path=krafla_event.scatangle --algorithm=iterate -m=1 --double-couple -n 5 --max_samples=100000 -i=PPolarity --convert --bin_scatangle -V 4 krafla_event_data_py36.inv
```
krafla_event_data_py36.inv was pickled with:

```
from example_data import krafla_event
data = krafla_event()
pickle.dump(data, open('krafla_event_data_py36.inv', 'wb'))
```

This being multiprocessing, the traceback isn't very useful, but here it is anyways:
```
*********



Event 1
--------

UID: krafla_event

Number of Random Samples: 49823 with 26372 location samples and 20 stations
Iterate algorithm chosen, maximum samples: 100000

Initialisation Complete

Beginning Inversion

/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.51.g44ce305.dirty-py3.6-linux-x86_64.egg/mtfit/inversion.py:200: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  marginalised=int(self.marginalise), location_samples_multipliers=ln_location_sample_multipliers)
/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.51.g44ce305.dirty-py3.6-linux-x86_64.egg/mtfit/inversion.py:200: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  marginalised=int(self.marginalise), location_samples_multipliers=ln_location_sample_multipliers)
/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.51.g44ce305.dirty-py3.6-linux-x86_64.egg/mtfit/inversion.py:200: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  marginalised=int(self.marginalise), location_samples_multipliers=ln_location_sample_multipliers)
/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.51.g44ce305.dirty-py3.6-linux-x86_64.egg/mtfit/inversion.py:200: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  marginalised=int(self.marginalise), location_samples_multipliers=ln_location_sample_multipliers)
/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.51.g44ce305.dirty-py3.6-linux-x86_64.egg/mtfit/inversion.py:200: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  marginalised=int(self.marginalise), location_samples_multipliers=ln_location_sample_multipliers)
Traceback (most recent call last):
  File "/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: 'NoneType' object is not callable

```

Which, I guess points to an issue with pickling the data before they're passed to the Pool, but I haven't the foggiest what the actuall issue would be.
 
All 5 jobs encounter this error and cease working, but no cleanup is done and the process hangs up.

I'm having a go at debugging, but I wanted to leave this here on the off chance that you had a hunch as to what was causing this.

-Chet

**Comment by djpugh** [comment]
Thanks, I'll have a look at it and see if I can fix it - are you running on linux or windows?

**Comment by cjhopp** [comment]
Yeah sorry, that's a useful bit of info. I'm on Ubuntu 14.04.

**Comment by djpugh** [comment]
OK, i'll need to set up a vagrant vm so I can test from windows on linux, but testing on mac now I think I have fixed it

**Comment by djpugh** [comment]
(Feels like it if my laptop fan is anything to go by...)

**Comment by djpugh** [comment]
I think that change fixes it - I'm currently travelling so can't easily test this properly but will have a go when I'm back home with some time, probably on Friday, feel free to test from PR #21 and let me know if that fixes it!

**Comment by cjhopp** [comment]
Unfortunately, I'm still getting the errors, (and, consequently, failing the 'laptop fan' test as well). I did have memory_proiler installed in both environments while getting the error above, though.

**Comment by djpugh** [comment]
OK, I'll set up a VM to test this weekend - just to check you are running ubuntu 14.04 (I'm assuming 64 bit) and python 3.6? - this links into #10 nicely as well

**Comment by djpugh** [comment]
Have got it happening as well - think it maybe the kill command not entering the queue properly as i ran again with a smaller number of samples and found it, whereas I gave up yesterday after a few minutes running when the laptop was getting warm!

**Comment by djpugh** [comment]
Will delve into it a bit more when I'm not quite so exhausted!

**Comment by cjhopp** [comment]
Yep! 64-bit 14.04 with Py3.6.

Same error on Py2.7 but with a *slightly* different traceback:
```
Traceback (most recent call last):
  File "/home/chet/anaconda3/envs/mtfit_27/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
TypeError: 'NoneType' object is not callable
```

Glad you were able to reproduce it!

**Comment by djpugh** [comment]
Done a load of diving through the code, and I think it is because the `ForwardTask` object is returning a `LnPDF` which doesn't have a pickle state, so need to add that in and test

**Comment by djpugh** [comment]
Yup, that seems to have fixed it now

**Comment by cjhopp** [comment]
Thanks for digging that one up! Workers all run to completion now on my end. There's a new error message during result parsing. I'll raise a new issue.
